---
config:
  layout: dagre
---
erDiagram

  CHARITY {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    VARCHAR CHARITY_NAME
    VARCHAR CHARITY_TYPE
    VARCHAR CHARITY_REGISTRATION_STATUS
    DATE DATE_OF_REGISTRATION
    DATE DATE_OF_REMOVAL
    VARCHAR CHARITY_REPORTING_STATUS
    DATE LATEST_ACC_FIN_PERIOD_START_DATE
    DATE LATEST_ACC_FIN_PERIOD_END_DATE
    NUMBER LATEST_INCOME
    NUMBER LATEST_EXPENDITURE
    VARCHAR CHARITY_CONTACT_ADDRESS1
    VARCHAR CHARITY_CONTACT_ADDRESS2
    VARCHAR CHARITY_CONTACT_ADDRESS3
    VARCHAR CHARITY_CONTACT_ADDRESS4
    VARCHAR CHARITY_CONTACT_ADDRESS5
    VARCHAR CHARITY_CONTACT_POSTCODE
    VARCHAR CHARITY_CONTACT_PHONE
    VARCHAR CHARITY_CONTACT_EMAIL
    VARCHAR CHARITY_CONTACT_WEB
    VARCHAR CHARITY_COMPANY_REGISTRATION_NUMBER
    BOOLEAN CHARITY_INSOLVENT
    BOOLEAN CHARITY_IN_ADMINISTRATION
    BOOLEAN CHARITY_PREVIOUSLY_EXCEPTED
    VARCHAR CHARITY_IS_CDF_OR_CIF
    BOOLEAN CHARITY_IS_CIO
    BOOLEAN CIO_IS_DISSOLVED
    DATE DATE_CIO_DISSOLUTION_NOTICE
    VARCHAR CHARITY_ACTIVITIES
    BOOLEAN CHARITY_GIFT_AID
    BOOLEAN CHARITY_HAS_LAND
  }

  CHARITY_ANNUAL_RETURN_HISTORY {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    DATE FIN_PERIOD_START_DATE
    DATE FIN_PERIOD_END_DATE
    VARCHAR AR_CYCLE_REFERENCE
    DATE REPORTING_DUE_DATE
    DATE DATE_ANNUAL_RETURN_RECEIVED
    DATE DATE_ACCOUNTS_RECEIVED
    NUMBER TOTAL_GROSS_INCOME
    NUMBER TOTAL_GROSS_EXPENDITURE
    BOOLEAN ACCOUNTS_QUALIFIED
    BOOLEAN SUPPRESSION_IND
    VARCHAR SUPPRESSION_TYPE
  }

  CHARITY_AR_PARTA {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    BOOLEAN LATEST_FIN_PERIOD_SUBMITTED_IND
    NUMBER FIN_PERIOD_ORDER_NUMBER
    VARCHAR AR_CYCLE_REFERENCE
    DATE FIN_PERIOD_START_DATE
    DATE FIN_PERIOD_END_DATE
    DATE AR_DUE_DATE
    DATE AR_RECEIVED_DATE
    NUMBER TOTAL_GROSS_INCOME
    NUMBER TOTAL_GROSS_EXPENDITURE
    BOOLEAN CHARITY_RAISES_FUNDS_FROM_PUBLIC
    BOOLEAN CHARITY_PROFESSIONAL_FUNDRAISER
    BOOLEAN CHARITY_AGREEMENT_PROFESSIONAL_FUNDRAISER
    BOOLEAN CHARITY_COMMERCIAL_PARTICIPATOR
    BOOLEAN CHARITY_AGREEMENT_COMMERICAL_PARTICIPATOR
    BOOLEAN GRANT_MAKING_IS_MAIN_ACTIVITY
    BOOLEAN CHARITY_RECEIVES_GOVT_FUNDING_CONTRACTS
    NUMBER COUNT_GOVT_CONTRACTS
    BOOLEAN CHARITY_RECEIVES_GOVT_FUNDING_GRANTS
    NUMBER COUNT_GOVT_GRANTS
    NUMBER INCOME_FROM_GOVERNMENT_CONTRACTS
    NUMBER INCOME_FROM_GOVERNMENT_GRANTS
    BOOLEAN CHARITY_HAS_TRADING_SUBSIDIARY
    BOOLEAN TRUSTEE_ALSO_DIRECTOR_OF_SUBSIDIARY
    BOOLEAN DOES_TRUSTEE_RECEIVE_ANY_BENEFIT
    BOOLEAN TRUSTEE_PAYMENTS_ACTING_AS_TRUSTEE
    BOOLEAN TRUSTEE_RECEIVES_PAYMENTS_SERVICES
    BOOLEAN TRUSTEE_RECEIVES_OTHER_BENEFIT
    BOOLEAN TRUSTEE_RESIGNED_EMPLOYMENT
    BOOLEAN EMPLOYEES_SALARY_OVER_60K
    NUMBER COUNT_SALARY_BAND_60001_70000
    NUMBER COUNT_SALARY_BAND_70001_80000
    NUMBER COUNT_SALARY_BAND_80001_90000
    NUMBER COUNT_SALARY_BAND_90001_100000
    NUMBER COUNT_SALARY_BAND_100001_110000
    NUMBER COUNT_SALARY_BAND_110001_120000
    NUMBER COUNT_SALARY_BAND_120001_130000
    NUMBER COUNT_SALARY_BAND_130001_140000
    NUMBER COUNT_SALARY_BAND_140001_150000
    NUMBER COUNT_SALARY_BAND_150001_200000
    NUMBER COUNT_SALARY_BAND_200001_250000
    NUMBER COUNT_SALARY_BAND_250001_300000
    NUMBER COUNT_SALARY_BAND_300001_350000
    NUMBER COUNT_SALARY_BAND_350001_400000
    NUMBER COUNT_SALARY_BAND_400001_450000
    NUMBER COUNT_SALARY_BAND_450001_500000
    NUMBER COUNT_SALARY_BAND_OVER_500000
    NUMBER COUNT_VOLUNTEERS
  }

  CHARITY_AR_PARTB {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    BOOLEAN LATEST_FIN_PERIOD_SUBMITTED_IND
    NUMBER FIN_PERIOD_ORDER_NUMBER
    VARCHAR AR_CYCLE_REFERENCE
    DATE FIN_PERIOD_START_DATE
    DATE FIN_PERIOD_END_DATE
    DATE AR_DUE_DATE
    DATE AR_RECEIVED_DATE
    NUMBER INCOME_DONATIONS_AND_LEGACIES
    NUMBER INCOME_CHARITABLE_ACTIVITIES
    NUMBER INCOME_OTHER_TRADING_ACTIVITIES
    NUMBER INCOME_INVESTMENTS
    NUMBER INCOME_OTHER
    NUMBER INCOME_TOTAL_INCOME_AND_ENDOWMENTS
    NUMBER INCOME_LEGACIES
    NUMBER INCOME_ENDOWMENTS
    NUMBER EXPENDITURE_RAISING_FUNDS
    NUMBER EXPENDITURE_CHARITABLE_EXPENDITURE
    NUMBER EXPENDITURE_OTHER
    NUMBER EXPENDITURE_TOTAL
    NUMBER EXPENDITURE_INVESTMENT_MANAGEMENT
    NUMBER EXPENDITURE_GRANTS_INSTITUTION
    NUMBER EXPENDITURE_GOVERNANCE
    NUMBER EXPENDITURE_SUPPORT_COSTS
    NUMBER EXPENDITURE_DEPRECIATION
    NUMBER GAIN_LOSS_INVESTMENT
    NUMBER GAIN_LOSS_PENSION_FUND
    NUMBER GAIN_LOSS_REVALUATION_FIXED_INVESTMENT
    NUMBER GAIN_LOSS_OTHER
    NUMBER RESERVES
    NUMBER ASSETS_TOTAL_FIXED
    NUMBER ASSETS_OWN_USE
    NUMBER ASSETS_LONG_TERM_INVESTMENT
    NUMBER DEFINED_BENEFIT_PENSION_SCHEME
    NUMBER ASSETS_OTHER_ASSETS
    NUMBER ASSETS_TOTAL_LIABILITIES
    NUMBER ASSETS_CURRENT_INVESTMENT
    NUMBER ASSETS_TOTAL_ASSETS_AND_LIABILITIES
    NUMBER CREDITORS_ONE_YEAR_TOTAL_CURRENT
    NUMBER CREDITORS_FALLING_DUE_AFTER_ONE_YEAR
    NUMBER ASSETS_CASH
    NUMBER FUNDS_ENDOWMENT
    NUMBER FUNDS_UNRESTRICTED
    NUMBER FUNDS_RESTRICTED
    NUMBER FUNDS_TOTAL
    NUMBER COUNT_EMPLOYEES
    BOOLEAN CHARITY_ONLY_ACCOUNTS
    BOOLEAN CONSOLIDATED_ACCOUNTS
  }

  CHARITY_AREA_OF_OPERATION {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    VARCHAR GEOGRAPHIC_AREA_TYPE
    VARCHAR GEOGRAPHIC_AREA_DESCRIPTION
    VARCHAR PARENT_GEOGRAPHIC_AREA_TYPE
    VARCHAR PARENT_GEOGRAPHIC_AREA_DESCRIPTION
    BOOLEAN WELSH_IND
  }

  CHARITY_CLASSIFICATION {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    NUMBER CLASSIFICATION_CODE
    VARCHAR CLASSIFICATION_TYPE
    VARCHAR CLASSIFICATION_DESCRIPTION
  }

  CHARITY_EVENT_HISTORY {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    VARCHAR CHARITY_NAME
    NUMBER LINKED_CHARITY_NUMBER
    NUMBER CHARITY_EVENT_ORDER
    VARCHAR EVENT_TYPE
    DATE DATE_OF_EVENT
    VARCHAR REASON
    NUMBER ASSOC_ORGANISATION_NUMBER
    NUMBER ASSOC_REGISTERED_CHARITY_NUMBER
    VARCHAR ASSOC_CHARITY_NAME
  }

  CHARITY_GOVERNING_DOCUMENT {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    VARCHAR GOVERNING_DOCUMENT_DESCRIPTION
    VARCHAR CHARITABLE_OBJECTS
    VARCHAR AREA_OF_BENEFIT
  }

  CHARITY_OTHER_NAMES {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    NUMBER CHARITY_NAME_ID
    VARCHAR CHARITY_NAME_TYPE
    VARCHAR CHARITY_NAME
  }

  CHARITY_OTHER_REGULATORS {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER REGULATOR_ORDER
    VARCHAR REGULATOR_NAME
    VARCHAR REGULATOR_WEB_URL
  }

  CHARITY_POLICY {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    VARCHAR POLICY_NAME
  }

  CHARITY_PUBLISHED_REPORT {
    DATE DATE_OF_EXTRACT
    NUMBER CHARITY_ID
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    VARCHAR REPORT_NAME
    VARCHAR REPORT_LOCATION
    DATE DATE_PUBLISHED
  }

  CHARITY_TRUSTEE {
    DATE DATE_OF_EXTRACT
    NUMBER ORGANISATION_NUMBER
    NUMBER REGISTERED_CHARITY_NUMBER
    NUMBER LINKED_CHARITY_NUMBER
    NUMBER TRUSTEE_ID
    VARCHAR TRUSTEE_NAME
    BOOLEAN TRUSTEE_IS_CHAIR
    CHAR INDIVIDUAL_OR_ORGANISATION
    DATE TRUSTEE_DATE_OF_APPOINTMENT
  }

  %% Relationships (logical FKs implied by extract keys)
  CHARITY ||--o{ CHARITY_ANNUAL_RETURN_HISTORY : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_AR_PARTA : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_AR_PARTB : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_AREA_OF_OPERATION : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_CLASSIFICATION : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_EVENT_HISTORY : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_GOVERNING_DOCUMENT : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_OTHER_NAMES : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_OTHER_REGULATORS : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_POLICY : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_TRUSTEE : ORGANISATION_NUMBER
  CHARITY ||--o{ CHARITY_PUBLISHED_REPORT : "CHARITY_ID (organisation_number)"

  %% Self-referential association (events referencing another charity)
  CHARITY_EVENT_HISTORY }o--o| CHARITY : ASSOC_ORGANISATION_NUMBER
