-- =========================
-- 1) CHARITY
-- =========================
CREATE OR REPLACE TABLE CHARITY (
  DATE_OF_EXTRACT                      DATE,
  ORGANISATION_NUMBER                  NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER            NUMBER(38,0),
  LINKED_CHARITY_NUMBER                NUMBER(38,0),
  CHARITY_NAME                         VARCHAR,
  CHARITY_TYPE                         VARCHAR,
  CHARITY_REGISTRATION_STATUS          VARCHAR,
  DATE_OF_REGISTRATION                 DATE,
  DATE_OF_REMOVAL                      DATE,
  CHARITY_REPORTING_STATUS             VARCHAR,
  LATEST_ACC_FIN_PERIOD_START_DATE     DATE,
  LATEST_ACC_FIN_PERIOD_END_DATE       DATE,
  LATEST_INCOME                        NUMBER(38,2),
  LATEST_EXPENDITURE                   NUMBER(38,2),
  CHARITY_CONTACT_ADDRESS1             VARCHAR,
  CHARITY_CONTACT_ADDRESS2             VARCHAR,
  CHARITY_CONTACT_ADDRESS3             VARCHAR,
  CHARITY_CONTACT_ADDRESS4             VARCHAR,
  CHARITY_CONTACT_ADDRESS5             VARCHAR,
  CHARITY_CONTACT_POSTCODE             VARCHAR,
  CHARITY_CONTACT_PHONE                VARCHAR,
  CHARITY_CONTACT_EMAIL                VARCHAR,
  CHARITY_CONTACT_WEB                  VARCHAR,
  CHARITY_COMPANY_REGISTRATION_NUMBER  VARCHAR,
  CHARITY_INSOLVENT                    BOOLEAN,
  CHARITY_IN_ADMINISTRATION            BOOLEAN,
  CHARITY_PREVIOUSLY_EXCEPTED          BOOLEAN,
  CHARITY_IS_CDF_OR_CIF                VARCHAR,
  CHARITY_IS_CIO                       BOOLEAN,
  CIO_IS_DISSOLVED                     BOOLEAN,
  DATE_CIO_DISSOLUTION_NOTICE          DATE,
  CHARITY_ACTIVITIES                   VARCHAR,
  CHARITY_GIFT_AID                     BOOLEAN,
  CHARITY_HAS_LAND                     BOOLEAN
);

-- =========================
-- 2) CHARITY_ANNUAL_RETURN_HISTORY
-- =========================
CREATE OR REPLACE TABLE CHARITY_ANNUAL_RETURN_HISTORY (
  DATE_OF_EXTRACT              DATE,
  ORGANISATION_NUMBER          NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER    NUMBER(38,0),
  FIN_PERIOD_START_DATE        DATE,
  FIN_PERIOD_END_DATE          DATE,
  AR_CYCLE_REFERENCE           VARCHAR,
  REPORTING_DUE_DATE           DATE,
  DATE_ANNUAL_RETURN_RECEIVED  DATE,
  DATE_ACCOUNTS_RECEIVED       DATE,
  TOTAL_GROSS_INCOME           NUMBER(38,2),
  TOTAL_GROSS_EXPENDITURE      NUMBER(38,2),
  ACCOUNTS_QUALIFIED           BOOLEAN,
  SUPPRESSION_IND              BOOLEAN,
  SUPPRESSION_TYPE             VARCHAR
);

-- =========================
-- 3) CHARITY_AR_PARTA
-- =========================
CREATE OR REPLACE TABLE CHARITY_AR_PARTA (
  DATE_OF_EXTRACT                         DATE,
  ORGANISATION_NUMBER                     NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER               NUMBER(38,0),
  LATEST_FIN_PERIOD_SUBMITTED_IND         BOOLEAN,
  FIN_PERIOD_ORDER_NUMBER                 NUMBER(38,0),   -- tinyint
  AR_CYCLE_REFERENCE                      VARCHAR,
  FIN_PERIOD_START_DATE                   DATE,
  FIN_PERIOD_END_DATE                     DATE,
  AR_DUE_DATE                             DATE,
  AR_RECEIVED_DATE                        DATE,
  TOTAL_GROSS_INCOME                      NUMBER(38,2),
  TOTAL_GROSS_EXPENDITURE                 NUMBER(38,2),
  CHARITY_RAISES_FUNDS_FROM_PUBLIC        BOOLEAN,
  CHARITY_PROFESSIONAL_FUNDRAISER         BOOLEAN,
  CHARITY_AGREEMENT_PROFESSIONAL_FUNDRAISER BOOLEAN,
  CHARITY_COMMERCIAL_PARTICIPATOR         BOOLEAN,
  CHARITY_AGREEMENT_COMMERICAL_PARTICIPATOR BOOLEAN,
  GRANT_MAKING_IS_MAIN_ACTIVITY           BOOLEAN,
  CHARITY_RECEIVES_GOVT_FUNDING_CONTRACTS BOOLEAN,
  COUNT_GOVT_CONTRACTS                    NUMBER(38,0),
  CHARITY_RECEIVES_GOVT_FUNDING_GRANTS    BOOLEAN,
  COUNT_GOVT_GRANTS                       NUMBER(38,0),
  INCOME_FROM_GOVERNMENT_CONTRACTS        NUMBER(38,2),
  INCOME_FROM_GOVERNMENT_GRANTS           NUMBER(38,2),
  CHARITY_HAS_TRADING_SUBSIDIARY          BOOLEAN,
  TRUSTEE_ALSO_DIRECTOR_OF_SUBSIDIARY     BOOLEAN,
  DOES_TRUSTEE_RECEIVE_ANY_BENEFIT        BOOLEAN,
  TRUSTEE_PAYMENTS_ACTING_AS_TRUSTEE      BOOLEAN,
  TRUSTEE_RECEIVES_PAYMENTS_SERVICES      BOOLEAN,
  TRUSTEE_RECEIVES_OTHER_BENEFIT          BOOLEAN,
  TRUSTEE_RESIGNED_EMPLOYMENT             BOOLEAN,
  EMPLOYEES_SALARY_OVER_60K               BOOLEAN,
  COUNT_SALARY_BAND_60001_70000           NUMBER(38,0),
  COUNT_SALARY_BAND_70001_80000           NUMBER(38,0),
  COUNT_SALARY_BAND_80001_90000           NUMBER(38,0),
  COUNT_SALARY_BAND_90001_100000          NUMBER(38,0),
  COUNT_SALARY_BAND_100001_110000         NUMBER(38,0),
  COUNT_SALARY_BAND_110001_120000         NUMBER(38,0),
  COUNT_SALARY_BAND_120001_130000         NUMBER(38,0),
  COUNT_SALARY_BAND_130001_140000         NUMBER(38,0),
  COUNT_SALARY_BAND_140001_150000         NUMBER(38,0),
  COUNT_SALARY_BAND_150001_200000         NUMBER(38,0),
  COUNT_SALARY_BAND_200001_250000         NUMBER(38,0),
  COUNT_SALARY_BAND_250001_300000         NUMBER(38,0),
  COUNT_SALARY_BAND_300001_350000         NUMBER(38,0),
  COUNT_SALARY_BAND_350001_400000         NUMBER(38,0),
  COUNT_SALARY_BAND_400001_450000         NUMBER(38,0),
  COUNT_SALARY_BAND_450001_500000         NUMBER(38,0),
  COUNT_SALARY_BAND_OVER_500000           NUMBER(38,0),
  COUNT_VOLUNTEERS                        NUMBER(38,0)
);

-- =========================
-- 4) CHARITY_AR_PARTB
-- =========================
CREATE OR REPLACE TABLE CHARITY_AR_PARTB (
  DATE_OF_EXTRACT                      DATE,
  ORGANISATION_NUMBER                  NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER            NUMBER(38,0),
  LATEST_FIN_PERIOD_SUBMITTED_IND      BOOLEAN,
  FIN_PERIOD_ORDER_NUMBER              NUMBER(38,0), -- tinyint
  AR_CYCLE_REFERENCE                   VARCHAR,
  FIN_PERIOD_START_DATE                DATE,
  FIN_PERIOD_END_DATE                  DATE,
  AR_DUE_DATE                          DATE,
  AR_RECEIVED_DATE                     DATE,
  INCOME_DONATIONS_AND_LEGACIES        NUMBER(38,2),
  INCOME_CHARITABLE_ACTIVITIES         NUMBER(38,2),
  INCOME_OTHER_TRADING_ACTIVITIES      NUMBER(38,2),
  INCOME_INVESTMENTS                   NUMBER(38,2),
  INCOME_OTHER                         NUMBER(38,2),
  INCOME_TOTAL_INCOME_AND_ENDOWMENTS   NUMBER(38,2),
  INCOME_LEGACIES                      NUMBER(38,2),
  INCOME_ENDOWMENTS                    NUMBER(38,2),
  EXPENDITURE_RAISING_FUNDS            NUMBER(38,2),
  EXPENDITURE_CHARITABLE_EXPENDITURE   NUMBER(38,2),
  EXPENDITURE_OTHER                    NUMBER(38,2),
  EXPENDITURE_TOTAL                    NUMBER(38,2),
  EXPENDITURE_INVESTMENT_MANAGEMENT    NUMBER(38,2),
  EXPENDITURE_GRANTS_INSTITUTION       NUMBER(38,2),
  EXPENDITURE_GOVERNANCE               NUMBER(38,2),
  EXPENDITURE_SUPPORT_COSTS            NUMBER(38,2),
  EXPENDITURE_DEPRECIATION             NUMBER(38,2),
  GAIN_LOSS_INVESTMENT                 NUMBER(38,2),
  GAIN_LOSS_PENSION_FUND               NUMBER(38,2),
  GAIN_LOSS_REVALUATION_FIXED_INVESTMENT NUMBER(38,2),
  GAIN_LOSS_OTHER                      NUMBER(38,2),
  RESERVES                             NUMBER(38,2),
  ASSETS_TOTAL_FIXED                   NUMBER(38,2),
  ASSETS_OWN_USE                       NUMBER(38,2),
  ASSETS_LONG_TERM_INVESTMENT          NUMBER(38,2),
  DEFINED_BENEFIT_PENSION_SCHEME       NUMBER(38,2),
  ASSETS_OTHER_ASSETS                  NUMBER(38,2),
  ASSETS_TOTAL_LIABILITIES             NUMBER(38,2),
  ASSETS_CURRENT_INVESTMENT            NUMBER(38,2),
  ASSETS_TOTAL_ASSETS_AND_LIABILITIES  NUMBER(38,2),
  CREDITORS_ONE_YEAR_TOTAL_CURRENT     NUMBER(38,2),
  CREDITORS_FALLING_DUE_AFTER_ONE_YEAR NUMBER(38,2),
  ASSETS_CASH                          NUMBER(38,2),
  FUNDS_ENDOWMENT                      NUMBER(38,2),
  FUNDS_UNRESTRICTED                   NUMBER(38,2),
  FUNDS_RESTRICTED                     NUMBER(38,2),
  FUNDS_TOTAL                          NUMBER(38,2),
  COUNT_EMPLOYEES                      NUMBER(38,0),
  CHARITY_ONLY_ACCOUNTS                BOOLEAN,
  CONSOLIDATED_ACCOUNTS                BOOLEAN
);

-- =========================
-- 5) CHARITY_AREA_OF_OPERATION
-- =========================
CREATE OR REPLACE TABLE CHARITY_AREA_OF_OPERATION (
  DATE_OF_EXTRACT                 DATE,
  ORGANISATION_NUMBER             NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER       NUMBER(38,0),
  LINKED_CHARITY_NUMBER           NUMBER(38,0),
  GEOGRAPHIC_AREA_TYPE            VARCHAR,
  GEOGRAPHIC_AREA_DESCRIPTION     VARCHAR,
  PARENT_GEOGRAPHIC_AREA_TYPE     VARCHAR,
  PARENT_GEOGRAPHIC_AREA_DESCRIPTION VARCHAR,
  WELSH_IND                       BOOLEAN
);

-- =========================
-- 6) CHARITY_CLASSIFICATION
-- =========================
CREATE OR REPLACE TABLE CHARITY_CLASSIFICATION (
  DATE_OF_EXTRACT              DATE,
  ORGANISATION_NUMBER          NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER    NUMBER(38,0),
  LINKED_CHARITY_NUMBER        NUMBER(38,0),
  CLASSIFICATION_CODE          NUMBER(38,0),
  CLASSIFICATION_TYPE          VARCHAR,
  CLASSIFICATION_DESCRIPTION   VARCHAR
);

-- =========================
-- 7) CHARITY_EVENT_HISTORY
-- =========================
CREATE OR REPLACE TABLE CHARITY_EVENT_HISTORY (
  DATE_OF_EXTRACT                 DATE,
  ORGANISATION_NUMBER             NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER       NUMBER(38,0),
  CHARITY_NAME                    VARCHAR,
  LINKED_CHARITY_NUMBER           NUMBER(38,0),
  CHARITY_EVENT_ORDER             NUMBER(38,0),  -- bigint
  EVENT_TYPE                      VARCHAR,
  DATE_OF_EVENT                   DATE,
  REASON                          VARCHAR,
  ASSOC_ORGANISATION_NUMBER       NUMBER(38,0),
  ASSOC_REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  ASSOC_CHARITY_NAME              VARCHAR
);

-- =========================
-- 8) CHARITY_GOVERNING_DOCUMENT
-- =========================
CREATE OR REPLACE TABLE CHARITY_GOVERNING_DOCUMENT (
  DATE_OF_EXTRACT                DATE,
  ORGANISATION_NUMBER            NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER      NUMBER(38,0),
  LINKED_CHARITY_NUMBER          NUMBER(38,0),
  GOVERNING_DOCUMENT_DESCRIPTION VARCHAR,
  CHARITABLE_OBJECTS             VARCHAR,
  AREA_OF_BENEFIT                VARCHAR
);

-- =========================
-- 9) CHARITY_OTHER_NAMES
-- =========================
CREATE OR REPLACE TABLE CHARITY_OTHER_NAMES (
  DATE_OF_EXTRACT           DATE,
  ORGANISATION_NUMBER       NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  LINKED_CHARITY_NUMBER     NUMBER(38,0),
  CHARITY_NAME_ID           NUMBER(38,0),
  CHARITY_NAME_TYPE         VARCHAR,
  CHARITY_NAME              VARCHAR
);

-- =========================
-- 10) CHARITY_OTHER_REGULATORS
-- =========================
CREATE OR REPLACE TABLE CHARITY_OTHER_REGULATORS (
  DATE_OF_EXTRACT           DATE,
  ORGANISATION_NUMBER       NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  REGULATOR_ORDER           NUMBER(38,0), -- bigint
  REGULATOR_NAME            VARCHAR,
  REGULATOR_WEB_URL         VARCHAR
);

-- =========================
-- 11) CHARITY_POLICY
-- =========================
CREATE OR REPLACE TABLE CHARITY_POLICY (
  DATE_OF_EXTRACT           DATE,
  ORGANISATION_NUMBER       NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  LINKED_CHARITY_NUMBER     NUMBER(38,0),
  POLICY_NAME               VARCHAR
);

-- =========================
-- 12) CHARITY_PUBLISHED_REPORT
-- =========================
CREATE OR REPLACE TABLE CHARITY_PUBLISHED_REPORT (
  DATE_OF_EXTRACT           DATE,
  CHARITY_ID                NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  LINKED_CHARITY_NUMBER     NUMBER(38,0),
  REPORT_NAME               VARCHAR,
  REPORT_LOCATION           VARCHAR,
  DATE_PUBLISHED            DATE
);

-- =========================
-- 13) CHARITY_TRUSTEE
-- =========================
CREATE OR REPLACE TABLE CHARITY_TRUSTEE (
  DATE_OF_EXTRACT          DATE,
  ORGANISATION_NUMBER      NUMBER(38,0),
  REGISTERED_CHARITY_NUMBER NUMBER(38,0),
  LINKED_CHARITY_NUMBER    NUMBER(38,0),
  TRUSTEE_ID               NUMBER(38,0),
  TRUSTEE_NAME             VARCHAR,
  TRUSTEE_IS_CHAIR         BOOLEAN,
  INDIVIDUAL_OR_ORGANISATION CHAR(1),
  TRUSTEE_DATE_OF_APPOINTMENT DATE
);
